### ISSUE TITLE
360 Media Download Issue

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#43] opened 2018-01-05 01:03 UTC

**Comment by josephinekao** [comment] 2018-01-05 01:04
"In subject 10 - 360 Media Production in lesson 7 'Spatial Audio ' there is information about SpatialAudio directory in course materials, but I am not able to find it. I have downloaded materials once again after contact with my mentor but thee are still only two raw videos and that's all. I think there should be also .pano file which was mentioned earlier in the course but again I could not find it."

**Comment by martinwilter** [comment] 2018-01-31 20:59
Duplicate of #31.

**Closed** 2018-01-31 21:01 UTC
Labels: C7B 360 Media Production, duplicate, impacts: course assets, issue: bug
