### ISSUE TITLE
performant lighting quiz bug

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#19] opened 2017-09-14 21:39 UTC
Lesson 7.6, Performant lighting

Bug that gives incorrect answer prompt regardless of what answer is submitted (see attached images)

**Comment by josephinekao** [comment] 2017-09-14 21:40
![Screen Shot 2017-08-29 at 4.56.41 PM (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b1b871b718f20011415912/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456fa6b7191a37cf1172d4f5b5e5ecc3c484746e5eb9539e6f4632adf0f4fffdb7f5a7dc33818a8ebd718b702e825884f85b1b8db4f93e03f2cf5979d0d6f405147d4a61760e28b41da59f141e04855a1173466e476377b45920c38.png)
![Screen Shot 2017-08-29 at 4.57.31 PM (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b1b871b718f20011415912/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456fa6b7191a37cf1172c4f5c5e5ecc3c484746e5eb9539e6f4632adf0f4fffdb7f5a7dc33818a8ebd718b702e825884f85b1b8db4f93e03f2cf5979d0d6f405147d4a61760e28b41da59fe41e04855a1173466e476327542940c38.png)
![Screen Shot 2017-08-29 at 4.57.19 PM (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b1b871b718f20011415912/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456fa6b7191a37cf1172c4f5e565ecc3c484746e5eb9539e6f4632adf0f4fffdb7f5a7dc33818a8ebd718b702e825884f85b1b8db4f93e03f2cf5979d0d6f405147d4a61760e28b41da59f141e04855a1173466e4763175429c0c38.png)

**Comment by martinwilter** [comment] 2017-09-14 23:03
This issue was fixed with issue #14.

It was not a bug. This is a checkbox quiz where one or more options might be the correct answer.

While addressing issue #14 we added a hint about possibly needing to select more than one option to get the correct answer.

**Closed** 2017-09-14 23:03 UTC
Labels: duplicate
